### PR TITLE
Async client for use with Python's asynchronous I/O + examples

### PR DESCRIPTION
**Pull request by brandur**
Here we add support for Python's built-in asyncio [1], a feature that's
commonly requested for library APIs because it enables very performant
code built on asynchronous I/O.

The change creates a second client class called `AsyncClient` along with
an `riversqlalchemy.AsyncDriver` to go with the original driver. This
design is based on SQLAlchemy's and the code that the Python sqlc plugin
generates. The APIs for the pair of clients and drivers are identical,
but one set has `async` annotations on everything and takes appropriate
inputs (like an async SQLAlchemy engine instead of synchronous one).

The final usage looks pretty close to non-async code (which I think is a
pretty reasonable outcome overall):

    engine = sqlalchemy.ext.asyncio.create_async_engine(dev_database_url(is_async=True))
    client = riverqueue.AsyncClient(riversqlalchemy.AsyncDriver(engine))

    insert_res = await client.insert(
        SortArgs(strings=["whale", "tiger", "bear"]),
        insert_opts=riverqueue.InsertOpts(
            unique_opts=riverqueue.UniqueOpts(by_period=900)
        ),
    )
    print(insert_res)

I also added a new `examples/` package that shows code for how to do
various things with River Python, and makes sure they're run in CI and
get static analysis from MyPy.

[1] https://docs.python.org/3/library/asyncio.html

### CODE REVIEW

**Comment by brandur** [comment]
cc @ewhauser This is the last big one I wanted to get your thoughts on to make sure it follows Python convention reasonably well. I still have to write more tests, but the broad API is all there. Thoughts?

**Review by ewhauser — APPROVED** [review]
LGTM

**Comment by brandur** [comment]
Woot. Thanks Eric! Going to finish off more tests, then bring this in.

**Comment by brandur** [comment]
Okay, I feel a little bad about this, but I pulled the Docker-based tests. I was having a ton of trouble getting async tests working in conjunction with them, and iterating was super slow because it had to go through GitHub Actions. I pushed the removal as a separate commit in case anyone feels strongly about bringing them back.

**Pull request merged**
